FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 18088

ENV TELEGRAM_BOT_TOKEN=""
ENV TELEGRAM_BOT_USERNAME=""
ENV TELEGRAM_BOT_ADMINS=""
ENV TELEGRAM_BOT_BASE=""
ENV APP_CHARS_PER_PAGE=3000
ENV TELEGRAM_BOT_WEBAPP_URL=https://xxx.xx.com
ENV CLOUD_R2_ACCESS_KEY=""
ENV CLOUD_R2_SECRET_KEY=""
ENV CLOUD_R2_ACCOUNT_ID=""
ENV CLOUD_R2_BUCKET_NAME=""
ENV CLOUD_R2_PUBLIC_DOMAIN=""
ENV CLOUDFLARE_API_TOKEN=""
ENV CLOUDFLARE_ZONES_BOOK_8VOID_SBS=""
ENV CLOUDFLARE_ZONES_ANOTHER_DOMAIN_COM=""

ENTRYPOINT ["java", "-jar", "app.jar"]
